### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by remenkoff** [wtsnz/Coordinator-Example#1]
Hi!

What about memory leaks? I just launched the app and moved from `orders` to `add order` screen and back `to orders` screen about 7-10 times, and memory consumption is growed up from 22.8 MB to 24.8 MB (see screenshot).

<img width="363" alt="2017-03-03 15 53 37" src="https://cloud.githubusercontent.com/assets/3461969/23551877/e85e9070-0029-11e7-8e47-7455aecdc542.png">

Thanks.

**Comment by remenkoff** [comment]
@wtsnz, I found solution for your example. Just declare your Optional delegates as a weak, like so:
```swift
weak var delegate: NewOrderCoordinatorDelegate? = nil
```
> (actually, `nil` here isn't required, cause Optionals are `nil` by default)

...and so:

```swift
weak var delegate: DrinkTypeControllerDelegate?
weak var delegate: SnackTypeViewControllerDelegate?
weak var delegate: SplashViewControllerDelegate?
```

And we get absolutely another picture:
<img width="447" alt="2017-03-08 18 52 19" src="https://cloud.githubusercontent.com/assets/3461969/23711261/642dd710-0430-11e7-9860-25fc3fe1e1c7.png">

All generations made in the following order: 
1. root -> add (cancel) -> root (x5 times);
2. root-> add (coffee) -> add (muffin) -> root (x5 times);
3. etc.

<img width="859" alt="2017-03-09 2 59 09" src="https://cloud.githubusercontent.com/assets/3461969/23729686/741e4706-0474-11e7-9728-c58c24e903a4.png">

What do you think about it? :)

**Comment by wtsnz** [comment]
Hey @remenkoff!

Thanks so much for this, awesome investigation work there! You're absolutely right, I forgot to mark the delegates as `weak` in this example 🙃 

I'll update the example code with the changes!
